'use strict';
// Original study mnemonics, not claims about word origins.
const studyNotes = {
'Forehead':['FRONT-al keeps FRONT in view. Frons ends in -ons.','Picture the FRONT of a cap resting on your forehead.','The forehead is the front of the head above the eyes.'],
'Skull':['Break cranium into CRA-NI-UM; cranial keeps CRANI-.','A cranium is a protective crash helmet for the brain.','The skull encloses and protects the brain.'],
'Face':['Facies ends in -ies; facial is FACE with the ending changed.','FACE → FACial: keep the FAC together.','The face includes the eyes, nose, and mouth used in sensing and expression.'],
'Mouth':['Oris ends in -is, not -us. Oral keeps OR-.','ORal reports come out of your mouth.','The mouth takes in food and helps form speech.'],
'Chin':['Mentis ends in -is; mental keeps MENT-.','Rest your chin on your hand while doing MENTal math.','Here mental names the chin region, not a thought process.'],
'Armpit':['Axilla has one x and two l letters: AX-ILL-A.','Picture two L-shaped arms lifted to expose the armpits.','The axilla is the area beneath the shoulder where arm and trunk meet.'],
'Upper arm':['Brachium: BRACH-I-UM. Brachial keeps BRACHI-.','Brace a bag against your BRACHium, your upper arm.','In regional anatomy, the arm is the shoulder-to-elbow segment.'],
'Front of elbow':['Antecubitis: ANTE-CUB-ITIS. Antecubital: ANTE-CUB-ITAL.','ANTE = front: picture the front elbow crease facing you.','This is the front of the elbow, not the bony point at the back.'],
'Forearm':['Antebrachium = ANTE + BRACHIUM. Do not lose the h.','Build the longer word by putting ANTE before BRACHIUM.','The forearm is the elbow-to-wrist segment.'],
'Wrist':['CAR-pus uses a, not o. Carpal shares the same CARP stem.','Picture your wrist turning a CAR steering wheel: CAR → CARpus.','The wrist connects hand and forearm and allows the hand to bend.'],
'Thumb':['Pollex has two l letters and ends in -ex.','Give a thumbs-up to a POLL: POLL + EX.','The thumb opposes the fingers to help grip objects.'],
'Palm':['Palma = PALM + A; palmar = PALM + AR.','The familiar word PALM is already inside both answers.','The palm is the inner surface of the hand used in gripping.'],
'Fingers':['Phalanges starts PH, not f: PHAL-ANG-ES. Phalangeal keeps PHALANGE-.','PHingers is a deliberately silly spelling cue for PHalanges.','Fingers help grip and manipulate objects; their bones are phalanges.'],
'Kneecap':['Patella has one t and two l letters: PA-TELL-A.','TELL a story about bumping your kneecap: pa-TELL-a.','The patella protects the front of the knee and helps the thigh muscles extend it.'],
'Leg':['Crus ends in -us; crural is CRUR-AL.','Picture CRUsing from knee to ankle.','The leg region runs from knee to ankle, rather than the whole lower limb.'],
'Ankle':['Tarsus: TAR-SUS. Tarsal shares TARS-.','Imagine stepping into TAR around your ankle.','The ankle region joins the leg and foot and contributes to walking.'],
'Toes':['Phalanges starts PH and ends -anges. Digital keeps DIGIT-.','Count your toe DIGITS like digits on a counter.','Toes help balance and push-off; their bones are phalanges.'],
'Great toe':['Hallux has two l letters and ends in x: HALL-UX.','Your big toe leads you down the HALL: HALL + UX.','The great toe contributes to balance and push-off in walking.'],
'Eye':['Oculus is OC-U-LUS; ocular keeps OCUL-. Orbital names the eye region.','Imagine a tiny O-shaped lens at the start of Oculus.','The eye detects light for vision.'],
'Cheek':['Bucca has two c letters: BUC-CA. Buccal adds l.','Two C-shaped cheeks: buCCa.','The cheeks form the sides of the mouth and help keep food between the teeth.'],
'Ear':['Auris ends in -is. Otic is O-T-I-C.','An AUdio reminder for AUris: both begin AU.','The ear is associated with hearing; the inner ear also supports balance.'],
'Nose':['Nasus ends in -us. Nasal keeps NAS-.','NASal spray goes in the nose.','The nose is involved in smell and conditions inhaled air.'],
'Neck':['Cervicis: CER-VIC-IS, ending in -is. Cervical: CER-VIC-AL.','Keep CERVIC, then choose IS for cervicis or AL for cervical.','Here the cervical region is the neck connecting head and trunk.'],
'Chest':['Thorax ends in x; thoracic is THOR-AC-IC. Keep the h after t.','Imagine THOR wearing chest armor: THORax.','The chest contains the heart and lungs and moves during breathing.'],
'Breast':['Mamma has three m letters altogether: MAM-MA. Mammary keeps MAMM-.','MAM-MA: two short chunks, with the m repeated at the join.','Mammary glands in the breast can produce milk.'],
'Abdomen':['Abdomen: AB-DO-MEN. Abdominal changes the ending to -inal.','Think ABDO before your abdominal exercise.','The abdomen contains many digestive organs.'],
'Navel':['Umbilicus: UM-BIL-I-CUS. Umbilical keeps UMBILIC-.','Connect UMBILicus to the UMBILical cord.','The navel marks the former attachment of the umbilical cord.'],
'Hip':['Coxal has an x: COX-AL. Coxa ends in a.','Picture an X beside the hip: coXal.','The hip region is where the thigh meets the pelvis.'],
'Pelvis':['Pelvis ends in -is; pelvic ends in -ic.','PELVI stays put while S changes to C.','The pelvis supports and transfers body weight toward the lower limbs.'],
'Groin':['Ing uen written together is INGUEN. Inguinal: IN-GUIN-AL.','Keep INGU together in both inguen and inguinal.','The groin is the junction of the upper thigh and trunk.'],
'Pubic region':['Pubis ends in -is; pubic ends in -ic.','PUBI stays put: pubi-S or pubi-C.','The pubic region lies at the front of the pelvis.'],
'Thigh':['Femur: FE-MUR. Femoral: FEM-OR-AL.','The FEMur belongs in the FEMoral thigh region.','The thigh is the hip-to-knee segment and contains the femur.'],
'Foot':['Pes is P-E-S; pedal keeps PED-.','Your foot presses a PEDal.','The foot supports weight and helps balance and propulsion.'],
'Trunk':['Trunk is the everyday term; torso is TOR-SO.','A tree trunk is its central support; your torso is your central body region.','The trunk includes the chest, abdomen, and pelvis.'],
'Shoulder':['Acromial: A-CRO-MI-AL. Acromion ends in -ion.','A CROW perched on your shoulder cues A-CRO-mial.','The acromial region is at the point of the shoulder.'],
'Back':['Dorsum ends in -um; dorsal keeps DORS-.','A dorsal fin is on a fish’s back: DORS → back.','The dorsal region is the back of the trunk.'],
'Back of elbow':['Olecranon: O-LE-CRA-NON. Olecranal ends in -al.','“Oh!” when you bump your elbow cues O-lecranon.','The olecranon forms the bony point at the back of the elbow.'],
'Lower back':['Lumbus: LUM-BUS. Lumbar changes -us to -ar.','A LUMbar cushion supports the lower back.','The lumbar region is the lower back between the ribs and pelvis.'],
'Sacral region':['Sacrum: SAC-RUM. Sacral keeps SACR-.','Picture a SAC-shaped cushion at the back of the pelvis.','The sacral region overlies the sacrum at the back of the pelvis.'],
'Hand':['Manus ends in -us; manual keeps MANU-.','MANUal work is done by hand.','The hand grips, manipulates, and senses objects.'],
'Buttock':['Gluteus: GLU-TE-US. Gluteal keeps GLUTE-.','Think of your GLUTE muscles when standing from a chair.','The gluteal region covers muscles that move and stabilize the hip.'],
'Back of knee':['Popliteus: POP-LIT-E-US. Popliteal: POP-LIT-E-AL.','Picture a POP of light behind your knee: POP-LIT.','This label identifies the back of the knee, not the kneecap.'],
'Calf':['Sura: SU-RA. Sural adds l.','Picture the calf SUrging upward when you rise onto your toes.','Calf muscles help lift the heel and push off during walking.'],
'Heel':['Calcaneus: CAL-CAN-E-US. Calcaneal keeps CALCANE-.','A CAN under your heel cues cal-CAN-eus.','The calcaneus forms the heel and helps bear weight.'],
'Sole of foot':['Planta = PLANT + A; plantar = PLANT + AR.','PLANT your foot on the ground: PLANTar.','The sole contacts the ground and supports the foot during standing and walking.'],
'Head':['Cephalon: CEPH-AL-ON. Cephalic: CEPH-AL-IC.','Picture a cap marked CEPH on your head.','The head contains the brain and several major sensory organs.'],
'Upper limb':['Upper extremity: EX-TREM-I-TY. Limb has a silent b.','The upper limb reaches from shoulder to fingertips.','This includes the arm, forearm, and hand.'],
'Lower limb':['Lower extremity: EX-TREM-I-TY. Limb has a silent b.','The lower limb reaches from hip to toes.','This includes the thigh, leg, and foot.']
};
