'use strict';
let studyEnabled=false,labelsUsed=false,quizViewBeforeStudy=null;
const headIds=[0,1,2,3,4,18,19,20,21,22];
function studyVisible(i){return viewMode==='head'?headIds.includes(i):viewMode==='both'||(viewMode==='front')===(regions[i].view==='Anterior')}
function studyCard(i){const r=regions[i],term=r.aliases[0],secondary=r.name.toLowerCase()===term.toLowerCase()?'':r.name;return `<button class="studylabel ${selected===i?'selected':''}" data-study-region="${i}" aria-pressed="${selected===i}"><span class="studybadge">${r.id}</span><span><b>${escape(term[0].toUpperCase()+term.slice(1))}</b><small>${escape(secondary)}</small></span></button>`}
function studyFigure(front,head=false){const ids=regions.map((_,i)=>i).filter(i=>head?headIds.includes(i):front?i<34:i>=34),left=ids.filter(i=>front?i<18:i<48),right=ids.filter(i=>!left.includes(i)),box=head?'735 145 285 155':front?'700 130 380 700':'1110 130 350 700';const [cropX,cropY,cropW,cropH]=box.split(' ').map(Number);const markers=ids.map(i=>{const r=regions[i];return `<g class="studymarker ${selected===i?'selected':''}" data-study-region="${i}" role="button" tabindex="0" aria-label="Study region ${r.id}: ${escape(r.name)}"><circle cx="${r.x}" cy="${r.y}" r="${i===20||i===21?6.5:9}"/><text x="${r.x}" y="${r.y+3}" text-anchor="middle" font-size="${i===20||i===21?7:9}">${r.id}</text></g>`}).join('');return `<section class="studypanel ${head?'headpanel':''}"><h3>${head?'Head & neck':front?'Anterior view':'Posterior view'}</h3><div class="studygrid"><div class="studyfigure"><svg viewBox="${box}" aria-label="${head?'Head detail':front?'Anterior':'Posterior'} study diagram"><defs><clipPath id="study-crop" clipPathUnits="userSpaceOnUse"><rect x="${cropX}" y="${cropY}" width="${cropW}" height="${cropH}"/></clipPath></defs><g clip-path="url(#study-crop)"><image href="worksheet.png" width="1527" height="859"/><rect x="1067" y="362" width="45" height="32" fill="white"/><rect x="1420" y="408" width="60" height="35" fill="white"/><rect x="1355" y="625" width="60" height="35" fill="white"/>${markers}</g></svg></div><div class="studyrail" tabindex="0" aria-label="Scrollable region names"><div class="studylisttitle">REGION INDEX <span>${ids.length} terms</span></div>${ids.sort((a,b)=>a-b).map(studyCard).join('')}</div></div></section>`}
function renderStudy(){document.body.classList.toggle('study-mode',studyEnabled);$('#labels').setAttribute('aria-checked',String(studyEnabled));$('#canvas').hidden=studyEnabled;$('#studysurface').hidden=!studyEnabled;$('#studydetail').hidden=!studyEnabled;$('#answerform').hidden=studyEnabled;$('#headview').hidden=!studyEnabled;$('#prompt').textContent=studyEnabled?'Select a term or marker to study its spelling and role.':'Follow the original black line from the selected number.';$('#viewboth').hidden=studyEnabled;if(!studyEnabled)return;const railTop=$('#studysurface').querySelector('.studyrail')?.scrollTop??0;$('#studysurface').innerHTML=viewMode==='head'?studyFigure(true,true):studyFigure(viewMode==='front');const rail=$('#studysurface').querySelector('.studyrail');if(rail)rail.scrollTop=railTop;const r=regions[selected];$('#studydetail').innerHTML=`<h3>${escape(r.aliases[0])}</h3><p class="studymeaning">${escape(r.name)}</p><p class="studyaccepted">Accepted names: ${escape(r.aliases.join(', '))}</p>${learningCard(selected,{kind:'correct'},true)}`;$('#studysurface').style.setProperty('--study-scale',zoom)}
function toggleStudy(){studyEnabled=!studyEnabled;if(studyEnabled){labelsUsed=true;quizViewBeforeStudy=viewMode;viewMode=regions[selected].view==='Anterior'?'front':'back';zoom=1;$('#answer').blur()}else{viewMode=quizViewBeforeStudy??'both';zoom=1;}updateView();fitCanvas();paint();requestAnimationFrame(followSelected)}
function wireStudy(){ $('#labels').onclick=toggleStudy;$('#headview').onclick=()=>setView('head');$('#studysurface').onclick=e=>{const target=e.target.closest('[data-study-region]');if(target)choose(Number(target.dataset.studyRegion))};$('#studysurface').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('g[data-study-region]')){e.preventDefault();choose(Number(e.target.dataset.studyRegion))}};$('#studysurface').onpointerover=e=>{const target=e.target.closest('[data-study-region]');if(!target)return;const id=target.dataset.studyRegion;$('#studysurface').querySelectorAll('[data-study-region]').forEach(el=>el.classList.toggle('hovered',el.dataset.studyRegion===id))};$('#studysurface').onpointerleave=()=>$('#studysurface').querySelectorAll('.hovered').forEach(el=>el.classList.remove('hovered'))}

function followStudySelection(){const root=$('#studysurface');for(const [containerSelector,targetSelector]of [['.studyrail','.studylabel.selected'],['.studyfigure','.studymarker.selected']]){const container=root.querySelector(containerSelector),target=root.querySelector(targetSelector);if(!container||!target)continue;const box=container.getBoundingClientRect(),item=target.getBoundingClientRect(),behavior=matchMedia('(prefers-reduced-motion: reduce)').matches||document.body.classList.contains('reduce')?'instant':'smooth';let top=container.scrollTop,left=container.scrollLeft;if(item.top<box.top+8||item.bottom>box.bottom-8)top+=(item.top+item.height/2)-(box.top+box.height/2);if(item.left<box.left+8||item.right>box.right-8)left+=(item.left+item.width/2)-(box.left+box.width/2);container.scrollTo({top:Math.max(0,top),left:Math.max(0,left),behavior})}}
